# Data Diri
title_pendaftaran = "//h1[contains(text(), 'Form Pendaftaran')]"
input_namaDepan = "//input[@placeholder='Nama Depan']"
input_namaBelakang = "//input[@placeholder='Nama Belakang']"
input_tempatLahir = "//input[@placeholder='Tempat Lahir']"
input_tglLahir = "//input[@placeholder='DD/MM/YYYY']"
choose_month_overlay = "//div[@aria-label='Open months overlay']"
choose_year_overlay = "//div[@aria-label='Open years overlay']"
input_KTP = "//input[@placeholder='Nomor KTP']"
btn_uploadKTP = "//button[contains(text(), 'Upload File')]"
upload_KTP = "//input[@type='file']"
checkbox_masaKTP = "//input[@type='checkbox']"
input_masaKTP = "//div[@class='dp__main dp__theme_light']/div/div[@class='dp__input_wrap']/input[@class='dp__pointer dp__input_readonly dp__input dp__input_icon_pad dp__input_reg undefined']"
checkbox_seumurHidup = "//input[@type='checkbox']"
btn_WNI = "//button[normalize-space()='WNI']"
btn_WNA = "//button[contains(text(), 'WNA')]"
input_provinsi = "//input[@aria-placeholder='Pilih Provinsi']"
input_kota = "//input[@aria-placeholder='Pilih Kota']"
textarea_alamatDomisili = "//label[contains(text(), 'Alamat Domisili')]/following-sibling::div//textarea"
input_noTelp = "//input[@placeholder='Nomor Telepon']"
input_pekerjaan = "//input[@aria-placeholder='Pilih Pekerjaan']"
input_namaPerusahaan = "//input[@placeholder='Nama Perusahaan']"
textarea_alamatPerusahaan = "//label[contains(text(), 'Alamat Perusahaan')]/following-sibling::div//textarea"
input_noTelpPerusahaan = "//input[@placeholder='Nomor Telepon Perusahaan']"
btn_tidakPunyaNPWP = "//button[normalize-space()='Tidak Ada']"
input_kendaraan = "//input[@aria-placeholder='Jenis Kendaraan']"
input_kendaraanDiCari = "//input[@aria-placeholder='Pilih Kendaraan']"
input_tujuanPembelian = "//input[@aria-placeholder='Pilih Tujuan']"
input_emailRegis = "//input[@placeholder='Email']"
input_passwordRegis = "//input[@placeholder='Masukkan Kata Sandi Baru']"
input_passwordRegisConfirm = "//input[@placeholder='Masukkan Ulang Kata Sandi Baru']"
btn_selanjutnya = "//button[normalize-space()='Selanjutnya']"
btn_Jan = "//div[@class='dp__overlay_row'][1]/div[@class='dp__overlay_col'][1]/div[@class='dp__overlay_cell dp__overlay_cell_pad']"
btn_2006 = "//div[@class='dp__overlay_row'][36]/div[@class='dp__overlay_col'][2]/div[@class='dp__overlay_cell dp__overlay_cell_pad']"
btn_01 = "//div[@class='dp__calendar_row'][1]/div[@class='dp__calendar_item'][7]/div[@class='dp__cell_inner dp__pointer dp__date_hover']"
btn_selectDate = "//div[@class='dp__action_row']/div[@class='dp__action_buttons']/span[@class='dp__action dp__select']"

# Data Pembayaran
input_noRek = "//input[contains(@placeholder,'Nomor Rekening')]"
input_bank = "//input[@aria-placeholder='Pilih Bank']"
input_namaPemilikRekening = "//input[contains(@placeholder,'Nama Pemilik Rekening')]"
input_sumberDana = "//input[@aria-placeholder='Pilih Sumber Tabungan']"
input_metodeBayar = "//input[contains(@aria-placeholder,'Pilih Metode Pembayaran')]"
btn_daftarForm = "//button[normalize-space()='Daftar']"
toast_berhasilDaftar = "//div[contains(text(), 'Data baru berhasil ditambahkan')]"